"""
Downloadable report generation for PersonaPath.
Generates a formatted Markdown report of the user's results.
"""

from datetime import datetime


def generate_markdown_report(
    scores: dict,
    personality_type: dict,
    career_matches: list,
    personality_matches: list,
    narrative: str,
    burnout: dict,
    leadership: dict,
) -> str:
    """Generate a complete Markdown report of the user's personality results."""
    
    now = datetime.now().strftime("%B %d, %Y")
    
    lines = [
        "# 🧠 PersonaPath Personality Report",
        f"*Generated on {now}*",
        "",
        "---",
        "",
        f"## {personality_type['emoji']} Your Personality Type: {personality_type['name']}",
        f"**{personality_type['tagline']}**",
        "",
        personality_type["description"],
        "",
        "---",
        "",
        "## 📊 Big Five Trait Scores",
        "",
        "| Trait | Score | Level |",
        "|-------|-------|-------|",
    ]

    for trait, score in scores.items():
        level = "High" if score >= 65 else ("Low" if score <= 35 else "Moderate")
        lines.append(f"| {trait} | {score:.1f} / 100 | {level} |")

    lines += [
        "",
        "---",
        "",
        "## 💼 Top Career Matches",
        "",
    ]

    for i, match in enumerate(career_matches, 1):
        lines += [
            f"### {i}. {match['emoji']} {match['name']} — {match['score']:.1f}% Match",
            f"*{match['tagline']}*",
            "",
            match["description"],
            "",
            f"**Work Style:** {match['work_style']}",
            f"**Environment:** {match['environment']}",
            f"**Why You Match:** {match['explanation']}",
            "",
        ]

    lines += [
        "---",
        "",
        "## 🌟 Famous Personality Matches",
        "",
    ]

    for match in personality_matches:
        lines += [
            f"### {match['emoji']} {match['name']} — {match['score']:.1f}% Similarity",
            f"*{match['descriptor']} · {match['field']}*",
            "",
            match["bio"],
            "",
            f"> \"{match['quote']}\"",
            "",
        ]

    lines += [
        "---",
        "",
        "## 📖 Personality Narrative",
        "",
        narrative,
        "",
        "---",
        "",
        "## 🔋 Additional Insights",
        "",
        f"**Burnout Vulnerability:** {burnout['level']} ({burnout['score']:.1f}/100)",
        f"*{burnout['advice']}*",
        "",
        f"**Leadership Style:** {leadership['emoji']} {leadership['style']}",
        f"*{leadership['desc']}*",
        "",
        "---",
        "",
        "*This report was generated by PersonaPath — a psychology-inspired career and personality platform.*",
        "*Results are based on the Big Five (OCEAN) personality model.*",
    ]

    return "\n".join(lines)
